name: Deploy to demo site.
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        username: ${{ secrets.DEMO_USER }}
        server: ${{ secrets.DEMO_SERVER }}
        private_key: ${{ secrets.DEMO_PRIVATE_KEY }}
        remote_path: ${{ secrets.DEMO_DIR }}
