name: Deploy to demo site.
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: git-ftp-action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ${{ secrets.DEMO_URL }}
        ftp-username: ${{ secrets.DEMO_USER }}
        ftp-password: ${{ secrets.DEMO_PASSWORD }}