name: Deploy to demo site.
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.DEMO_SERVER }}
        USERNAME: ${{ secrets.DEMO_USER }}
        KEY: ${{ secrets.DEMO_PRIVATE_KEY }}
      with:
        target: ${{ secrets.DEMO_DIR }}
